groups:
  - name: "ETL_Alerts"
    rules:
      - alert: "GoroutineLeak"
        expr: deriv(etl_goroutines[5m]) > 0
        for: 5m
        labels:
          severity: "critical"
        annotations:
          summary: "Potential goroutine leak detected"
          description: "The number of goroutines has been strictly increasing over the last 5 minutes."

      - alert: "HighGCPause"
        expr: sum(rate(etl_gc_pause_ms_sum[1m])) / sum(rate(etl_gc_pause_ms_count[1m])) > 10
        for: 1m
        labels:
          severity: "warning"
        annotations:
          summary: "High GC pause times detected"
          description: "The average GC pause time has exceeded 10ms over the last minute."
