{
 "title": "Golden Signals",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(etl_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Errors (5xx Ratio)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(etl_http_requests_total{status=~\"5..\"}[1m]) / rate(etl_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(etl_http_request_duration_seconds_sum[1m])) / sum(rate(etl_http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Saturation (Goroutines)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "etl_goroutines" }
   ]
  },
  {
   "title": "System Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"etl_logs\"}"
    }
   ]
  }
 ]
}