groups:
  - name: resource_utilization
    rules:
      - alert: GoroutineLeak
        expr: deriv(etl_goroutines[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Potential Goroutine Leak"
          description: "Goroutines have been steadily increasing over the last 5 minutes."

      - alert: HighGCPause
        expr: sum(rate(etl_gc_pause_ms_sum[1m])) / sum(rate(etl_gc_pause_ms_count[1m])) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High GC Pause Times"
          description: "Average GC pause time is > 5ms over the last 1 minute."
