groups:
  - name: etl_alerts
    rules:
      - alert: HighGoroutineGrowth
        expr: deriv(etl_goroutines[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Continuous growth in goroutines"
          description: "The number of goroutines has been continuously increasing over the last 5 minutes."

      - alert: HighGCPause
        expr: sum(rate(etl_gc_pause_ms_sum[1m])) / sum(rate(etl_gc_pause_ms_count[1m])) > 20
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High GC Pause Time"
          description: "The average GC pause time has exceeded 20ms over the last minute."
