apiVersion: 1
groups:
  - orgId: 1
    name: "System Alerts"
    folder: "ETL Alerts"
    interval: "1m"
    rules:
      - uid: "gc_pause_alert"
        title: "High GC Pause"
        condition: "A"
        data:
          - refId: "A"
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: "Prometheus"
            model:
              expr: "sum(rate(etl_gc_pause_ms_sum[1m])) / sum(rate(etl_gc_pause_ms_count[1m])) > 20"
              intervalMs: 1000
              maxDataPoints: 43200
              refId: "A"
              type: "classic_conditions"
      - uid: "goroutine_leak_alert"
        title: "Goroutine Leak Detected"
        condition: "A"
        data:
          - refId: "A"
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: "Prometheus"
            model:
              expr: "deriv(etl_goroutines[5m]) > 0"
              intervalMs: 1000
              maxDataPoints: 43200
              refId: "A"
              type: "classic_conditions"
